title: Zihao Ding's Homepage
page-top-title: Zihao Ding
top-section-bg-text: Electrical Engineering and Computer Science
home-subtitle: Zihao Ding&ensp;|&ensp;丁 梓浩
copyright-text: '&copy; Zihao Ding 2025-2027. All Rights Reserved.'
